
      SUBROUTINE CALC_SPREAD(N,NMAX,NENS,ENPT,ENSEMBLE,TIME)
C
      IMPLICIT NONE
      INTEGER I,J,N,NENS,NMAX
      INTEGER ENPT(*)
      
      REAL*8 ENSEMBLE(NMAX,*),TIME
      REAL*8 ENMEAN(NMAX),ENSPREAD(NMAX)
      REAL*8 MINSPREAD,MAXSPREAD,MEANSPREAD


C compute ensemble spread
C
      MINSPREAD=1.0D10
      MAXSPREAD=0.0d0
      MEANSPREAD=0.0D0
      DO I=1,N
         ENMEAN(I)=0.0d0
         DO J=1,NENS
            ENMEAN(I)=ENMEAN(I)+ENSEMBLE(I,ENPT(J))
         END DO
         ENMEAN(I)=ENMEAN(I)/DFLOAT(NENS)
         ENSPREAD(I)=0.0d0
         DO J=1,NENS
            ENSPREAD(I)=ENSPREAD(I)+(ENSEMBLE(I,ENPT(J))-ENMEAN(I))**2.0
         END DO
         ENSPREAD(I)=ENSPREAD(I)/DFLOAT(NENS-1)
         MEANSPREAD=MEANSPREAD+ENSPREAD(I)
         IF (ENSPREAD(I).LT.MINSPREAD) THEN
            MINSPREAD=ENSPREAD(I)
         END IF
         IF (ENSPREAD(I).GT.MAXSPREAD) THEN
            MAXSPREAD=ENSPREAD(I)
         END IF
      END DO
      MEANSPREAD=MEANSPREAD/DFLOAT(N)
     
      WRITE(2010,*) TIME,MINSPREAD,MEANSPREAD,MAXSPREAD
      RETURN
      END
